name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

# Ensure only one run per commit SHA (e.g., when pushing a tag for the same commit)
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Generate PNG logo from SVG for README fallback
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          mkdir -p branding
          convert -background none branding/repo-logo.svg -resize 256x256 branding/repo-logo.png || true

      - name: Build Debug APK
        run: ./gradlew assembleDebug -x lint

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Prepare signing keystore (on tag only)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SIGNING_KEYSTORE_B64: ${{ secrets.SIGNING_KEYSTORE_B64 }}
        run: |
          if [ -z "$SIGNING_KEYSTORE_B64" ]; then
            echo "No keystore secret set; skipping release signing"; exit 0; fi
          echo "$SIGNING_KEYSTORE_B64" | base64 -d > keystore.jks

      - name: Build Release APK (signed if secrets provided)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SIGNING_KEYSTORE: ${{ github.workspace }}/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          if [ -f keystore.jks ]; then
            ./gradlew assembleRelease -x lint
          else
            echo "No keystore; building unsigned release"; ./gradlew assembleRelease -x lint
          fi

      - name: Rename APKs for friendly asset names (on tag only)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          REF_NAME="${{ github.ref_name }}"
          mkdir -p dist
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            cp app/build/outputs/apk/debug/app-debug.apk "dist/OneDrive-Photos-Sync-${REF_NAME}-debug.apk"
          fi
          if [ -f app/build/outputs/apk/release/app-release.apk ]; then
            cp app/build/outputs/apk/release/app-release.apk "dist/OneDrive-Photos-Sync-${REF_NAME}.apk"
          fi

      - name: Create GitHub Release and upload APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: OneDrive Photos Sync ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/OneDrive-Photos-Sync-${{ github.ref_name }}-debug.apk
            dist/OneDrive-Photos-Sync-${{ github.ref_name }}.apk